apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "EmissionsAPI"
  description: "Emissions API"
  links:
    - url: https://savitha.atlassian.net/wiki/spaces/~5570580e080c2a24874b35bd4a5a1bcb550b5e/pages/20742146/Architecture+guidance
      title: Architecture guidance
      icon: dashboard
  annotations:
    github.com/project-slug: tthctoinnovation/EmissionsAPI
    backstage.io/techdocs-ref: dir:.
    jira/project-key: "FLIG"
  tags: 
    -  nodejs
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/rapidlabs"
  subcomponentOf: "component:default/GreenMilesAPI"
  system: "sustainability"
  definition: |
        openapi: "3.0.0"
        info:
          version: 1.0.0
          title: Emissions API
        paths:
          /emission/options:
            get:
              summary: Get various search options
              responses:
                      '200':
                        description: OK
          /emission/{optionId}/parameter:
              get:
                summary: Get parameters available for given search options
                parameters:
                      - in: path
                        name: optionId
                        schema:
                          type: integer
                        required: true
                responses:
                      '200':
                        description: OK
