apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "EmissionsAPI"
  description: "Emissions API"
  annotations:
    github.com/project-slug: tthctoinnovation/EmissionsAPI
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/esavitha"
